### ISSUE TITLE
Page footer is truncated on the left

### ISSUE THREAD

**Issue by larseggert** [ietf/wiki.ietf.org#1]
The box that reads "Content is available under the Creative Commons Attribution License, by IETF Trust (CC BY 4.0). Please note that all content is covered by the IETF Note Well. | Powered by [Wiki.js](https://wiki.js.org/)" looks like this in my browser:
<img width="1316" alt="Screen Shot 2022-09-13 at 8 57 20" src="https://user-images.githubusercontent.com/200328/189844451-bec53a64-c381-493d-ae59-3558208e732b.png">

**Comment by NGPixel** [comment]
Fixed by temporarily overriding CSS.
Will apply the fix in the code base and it will be part of the next release.
