### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by larseggert** [ietf/wiki.ietf.org#12]
Can we get the wiki behind Cloudflare? It's pretty slow to use from Europe.

(Not only this one, but all the new IETF wikis.)

**Comment by rjsparks** [comment]
I think it might just be slow (not just from Europe).
And it's inherently an interactive application - editing will have to bypass cloudflare at a minimum.
I'll ask Nick what its current strategy is for using CDN.

**Comment by NGPixel** [comment]
It's not supposed to be this slow. Even from Montreal it's taking over 10s to load the homepage (without cache) which is abnormally slow. It should be closer to 1-2s.

We'll see if getting Cloudflare in front of it improve things but I suspect there might be something else in the pipeline causing this slowdown...

**Comment by larseggert** [comment]
<img width="1204" alt="Screen Shot 2022-09-30 at 9 44 01" src="https://user-images.githubusercontent.com/200328/193207347-a7581dde-38c1-4fa0-9c7e-0e3721dafaa8.png">

**Comment by larseggert** [comment]
Also
```
downloadable font: download failed (font-family: "Roboto" style:normal weight:500 stretch:100 src index:1): status=2152398850 source: https://wiki.ietf.org/_assets/fonts/Roboto-Medium.woff
downloadable font: download failed (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:2): status=2152398850 source: https://wiki.ietf.org/_assets/fonts/materialdesignicons-webfont.woff
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. [node.js:392](resource://devtools/server/actors/inspector/node.js)
There is a button with the key "copy-to-clipboard" registered already.
```

**Comment by NGPixel** [comment]
wiki.ietf.org is now behind cloudflare with everything at `/_assets` cached at the edge. The site now loads quickly. chairs and authors wikis will be added to cloudflare next week with the same optimizations.

I noticed the same massive slowdown on notes.ietf.org. So this seems to be a server wide issue, making the new infrastructure plan even more urgent...
