### ISSUE TITLE
`{.is-info}` not working if quote contains numbered list

### ISSUE THREAD

**Issue by larseggert** [ietf/wiki.ietf.org#14]
See https://wiki.ietf.org/en/group/iesg/UpcomingIETF

```
> 1. Quo vadis IETF: is the IETF ossified? (Ignacio Castro & Lars)
{.is-info}
```
is not blue

**Comment by NGPixel** [comment]
This is a limitation of the markdown-it-attrs library, as the class gets applied to the list and not the parent blockquote. A solution would be to add the markdown-it-decorate library to be able to specify classes directly on the blockquote.

**Comment by NGPixel** [comment]
Added markdown-it-decorate to Wiki.js 2.5.291, to be deployed after IETF 115. You'll be able to specify the target element for css classes using:

```
> 1. Quo vadis IETF: is the IETF ossified? (Ignacio Castro & Lars)
<!-- {blockquote:.is-info} -->
```

**Comment by NGPixel** [comment]
Wikis have been updated to the latest version (which includes the fix).
