### ISSUE TITLE
Empty lists are formatted weirdly

### ISSUE THREAD

**Issue by larseggert** [ietf/wiki.ietf.org#20]
<img width="600" alt="Screenshot 2023-01-10 at 10 31 23" src="https://user-images.githubusercontent.com/200328/211500472-15dca174-70d4-4fc1-8b5c-4557edbd5429.png">

**Comment by ghwood** [comment]
@larseggert I'm not sure if @NGPixel has changed anything, but his currently does not look as bad to me as your screenshot. I would consider it acceptable. WDYT?

<img width="973" alt="image" src="https://github.com/ietf/wiki.ietf.org/assets/5347540/178702da-e55c-4698-b119-8886960e6211">
