### ISSUE TITLE
URLs don't break

### ISSUE THREAD

**Issue by larseggert** [ietf/wiki.ietf.org#22]
URLs don't seem to break on https://wiki.ietf.org/meeting/115/sidemeetings, making the table awkwardly formatted. Can the config be tweaked so they are?

**Comment by JayDaley** [comment]
Rather than write the URL directly, they should be shown as a link for some shorter text.  I have gone through the first three tables on that page and done that to show what I mean.

**Comment by larseggert** [comment]
Except people won't do that consistently...

**Comment by larseggert** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/200328/232533856-213d4cdd-bb3a-47a9-a1ca-9a8b9dd2cf3a.png)

**Comment by ghwood** [comment]
Seems to be fixed now.
